version: "3.7"
services:
  rabbitmq:
    environment:
      - RABBITMQ_ERLANG_COOKIE="rabbitcookie"  
    networks:
      - back
    image:  rabbitmq:3.8.0-alpine
    ports: 
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 2
    configs:
      - source: enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
      - source: load_definitions
        target: /etc/rabbitmq/definitions.json

  consul:
    image: "consul"
    hostname: "consul"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8500:8500"
    networks:
      - back

configs:
  enabled_plugins:
    file: ./conf/enabled_plugins
  rabbitmq_conf:
    file: ./conf/rabbitmq.conf
  load_definitions:
    file: ./conf/definitions.json
      
networks:
  back:
