version: "3.7"
services:
   rabbitmq:
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_ERLANG_COOKIE="mycookie"  
    networks:
      - back
    image:  rabbitmq:3.8.0
    ports: 
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"
    deploy:
      mode: replicated
      replicas: 3
    configs:
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
      - source: enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
    command:  sh -c "sleep 10; rabbitmq-server;" 

   consul:
    image: "consul"
    hostname: "consul"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    networks:
      - back

configs:
  rabbitmq_conf:
    file: ./conf/rabbitmq.conf
  enabled_plugins:
    file: ./conf/enabled_plugins
      
networks:
  back:
